apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f3ht
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-f3ht@sha256:95c4b2cc3fabd9fef6b76d248984add1af9838ec9f9272dd2ce03ea91a3923d4
        name: my-nodejs
        resources: {}
status: {}
